=== GrizzlLearn/job4j_design/src/main/java/ru/job4j/serialization/xml/object.dtd
<!ELEMENT object (boolField, intField, stringField, objectField, arrayField)>
<!ELEMENT boolField (#PCDATA)>
<!ELEMENT intField (#PCDATA)>
<!ELEMENT stringField (#PCDATA)>
<!ELEMENT objectField (object1)>
<!ELEMENT object1 (stringField, intField)>
<!ELEMENT arrayField (array)>
<!ELEMENT array (element+)>
<!ELEMENT element (#PCDATA)>

=== GrizzlLearn/job4j_design/src/main/java/ru/job4j/serialization/xml/example.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE object SYSTEM "object.dtd">
<object>
    <boolField>true</boolField>
    <intField>42</intField>
    <stringField>Hello, world!</stringField>
    <objectField>
        <object1>
            <stringField>Inner object</stringField>
            <intField>123</intField>
        </object1>
    </objectField>
    <arrayField>
        <array>
            <element>Item 1</element>
            <element>Item 2</element>
            <element>Item 3</element>
        </array>
    </arrayField>
</object>
